# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20171025_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.profile_image_upload_handler),
        ),
    ]
